sso-auth-server: http://localhost:8082/ssoauth # sso-server地址


server:
  port: 8084
  servlet:
    context-path: /orderSystem
spring:
  profiles:
    active: dev
  application:
    name: sso-ui2
security:
  oauth2:
    client:
      client-id: OrderManagement
      client-secret: order123
      user-authorization-uri: ${sso-auth-server}/oauth/authorize
      access-token-uri: ${sso-auth-server}/oauth/token
    resource:
      jwt:
        key-uri: ${sso-auth-server}/oauth/token_key