sso-auth-server: http://localhost:8082/ssoauth # sso-server地址
server:
  port: 8083
  servlet:
    context-path: /memberSystem
spring:
  profiles:
    active: dev
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      user-authorization-uri: ${sso-auth-server}/oauth/authorize #请求认证地址
      access-token-uri: ${sso-auth-server}/oauth/token #请求令牌地址
    resource:
      jwt:
        key-uri: ${sso-auth-server}/oauth/token_key #解析jwt令牌所需要密钥地址
